import kids1 from "../assets/products/kids1.jfif";
import kids2 from "../assets/products/kids2.jfif";
import kids3 from "../assets/products/kids3.jfif";
import kids4 from "../assets/products/kids4.jfif";
import kids6 from "../assets/products/kids6.jfif";
import kids7 from "../assets/products/kids7.jfif";
import kids8 from "../assets/products/kids8.jfif";
import kids10 from "../assets/products/kids10.jfif";
import kids11 from "../assets/products/kids8.jfif";
import kidsshoes1 from "../assets/products/kidsshoes1.jfif";
import kidsshoes2 from "../assets/products/kidsshoes2.jfif";
import kidsshoes3 from "../assets/products/kidsshoes3.jfif";
import kidsshoes6 from "../assets/products/kidsshoes6.jfif";
import kidsshoes7 from "../assets/products/kidsshoes7.jfif";
import men3 from "../assets/products/men3.jfif";
import mencasual from "../assets/products/mencasual.jfif";
import mencasual3 from "../assets/products/mencasual3.jfif";
import mencasual8 from "../assets/products/mencasual8.jfif";
import menjacket1 from "../assets/products/menjacket1.jfif";
import menjacket2 from "../assets/products/menjacket2.jfif";
import menpants from "../assets/products/menpants.jfif";
import menpants3 from "../assets/products/menpants3.jfif";
import menpants5 from "../assets/products/menpants5.jfif";
import menshoes2 from "../assets/products/menshoes2.jfif";
import menshoes3 from "../assets/products/menshoes3.jfif";
import menshoes4 from "../assets/products/menshoes4.jfif";
import women3 from "../assets/products/women3.jfif";
import women4 from "../assets/products/women4.jfif";
import womenshoes1 from "../assets/products/womenshoes1.jfif";

import womensuits from "../assets/products/womensuits.jfif";
import womenpants2 from "../assets/products/womenpants2.jfif";
import womensuits2 from "../assets/products/womensuits2.jfif";
import womensuits4 from "../assets/products/womensuits4.jfif";
import womenjacket from "../assets/products/womenjacket.jfif";
import womenjacket1 from "../assets/products/womenjacket1.jfif";
import womenjacket2 from "../assets/products/womenjacket2.jfif";
import womencasual1 from "../assets/products/womencasual1.jfif";
import kidsdress from "../assets/products/What's new at Dannie and Lilou_.jfif";

export const products = [
  {
    id: 1,
    title: "Men's Classic White Shirt",
    rating: 4.5,
    price: 25.99,
    image: mencasual,
    description: "A timeless white shirt, perfect for formal occasions.",
    colors: ["white", "blue", "black"],
    category: ["men"],
    type: ["shirts", "formal"],
  },
  {
    id: 2,
    title: "Women's Black Leather Jacket",
    rating: 4.8,
    price: 79.99,
    image: womenjacket,
    description: "Stylish black leather jacket for casual outings.",
    colors: ["black", "brown"],
    category: ["women"],
    type: ["jackets", "casual"],
  },
  {
    id: 3,
    title: "Kids' Cartoon Print T-Shirt",
    rating: 4.7,
    price: 12.99,
    image: kids1,
    description: "Comfortable t-shirt with fun cartoon prints for kids.",
    colors: ["yellow", "red", "blue"],
    category: ["kids"],
    type: ["shirts", "casual"],
  },
  {
    id: 4,
    title: "Men's Slim Fit Jeans",
    rating: 4.6,
    price: 39.99,
    image: menpants,
    description: "Slim-fit jeans that offer both style and comfort.",
    colors: ["blue", "black", "gray"],
    category: ["men"],
    type: ["pants", "casual"],
  },
  {
    id: 5,
    title: "Women's Red High Heels",
    rating: 4.9,
    price: 59.99,
    image: womenshoes1,
    description: "Elegant high heels perfect for formal occasions.",
    colors: ["red", "black", "gold"],
    category: ["women"],
    type: ["high heels", "formal"],
  },
  {
    id: 6,
    title: "Kids' Winter Jacket",
    rating: 4.5,
    price: 49.99,
    image: kids4,
    description: "Warm and cozy jacket for kids during the winter.",
    colors: ["pink", "blue", "green"],
    category: ["kids"],
    type: ["jackets", "casual"],
  },
  {
    id: 7,
    title: "Men's Black Formal Suit",
    rating: 4.8,
    price: 120.99,
    image: men3,
    description: "A classy black suit for important business meetings.",
    colors: ["black", "gray", "navy"],
    category: ["men"],
    type: ["suits", "formal"],
  },
  {
    id: 8,
    title: "Women's Casual Blue Blouse",
    rating: 4.3,
    price: 29.99,
    image: womensuits2,
    description: "A stylish and comfortable blouse for daily wear.",
    colors: ["blue", "white", "pink"],
    category: ["women"],
    type: ["blouses", "casual"],
  },
  {
    id: 9,
    title: "Kids' Sports Shoes",
    rating: 4.7,
    price: 27.99,
    image: kidsshoes6,
    description: "Durable and lightweight shoes for kids' sports activities.",
    colors: ["white", "red", "black"],
    category: ["kids"],
    type: ["shoes", "casual"],
  },
  {
    id: 10,
    title: "Men's Casual Sneakers",
    rating: 4.6,
    price: 49.99,
    image: menshoes4,
    description: "Trendy sneakers for a casual look.",
    colors: ["white", "black", "gray"],
    category: ["men"],
    type: ["shoes", "casual"],
  },
  {
    id: 11,
    title: "Women's Evening Gown",
    rating: 4.9,
    price: 150.0,
    image: women4,
    description: "A stunning evening gown for special occasions.",
    colors: ["red", "blue", "gold"],
    category: ["women"],
    type: ["formal", "dresses"],
  },
  {
    id: 12,
    title: "Kids' Denim Overalls",
    rating: 4.4,
    price: 35.0,
    image: kids7,
    description: "Comfortable and stylish denim overalls for kids.",
    colors: ["blue", "black"],
    category: ["kids"],
    type: ["pants", "casual"],
  },
  {
    id: 13,
    title: "Men's Winter Coat",
    rating: 4.8,
    price: 99.99,
    image: menjacket2,
    description: "A warm and durable coat for the winter season.",
    colors: ["black", "gray", "brown"],
    category: ["men"],
    type: ["jackets", "formal"],
  },
  {
    id: 14,
    title: "Women's Stylish Handbag",
    rating: 4.7,
    price: 45.99,
    image: womenpants2,
    description: "A chic handbag to match any outfit.",
    colors: ["black", "beige", "red"],
    category: ["women"],
    type: ["accessories", "casual"],
  },
  {
    id: 15,
    title: "Kids' Colorful Raincoat",
    rating: 4.5,
    price: 25.0,
    image: kids10,
    description: "A vibrant raincoat to keep your kids dry and happy.",
    colors: ["yellow", "blue", "pink"],
    category: ["kids"],
    type: ["jackets", "casual"],
  },
  {
    id: 16,
    title: "Men's Plaid Shirt",
    rating: 4.3,
    price: 27.99,
    image: mencasual,
    description: "A casual plaid shirt for everyday wear.",
    colors: ["red", "green", "blue"],
    category: ["men"],
    type: ["shirts", "casual"],
  },
  {
    id: 178,
    title: "Women's Winter",
    rating: 4.6,
    price: 19.99,
    image: womenjacket2,
    description: "Soft and cozy woolen scarf to keep you warm.",
    colors: ["gray", "red", "blue"],
    category: ["women"],
    type: ["accessories", "casual"],
  },
  {
    id: 18,
    title: "Kids' Coat",
    rating: 4.7,
    price: 29.99,
    image: kids1,
    description: "Trendy hoodie with vibrant prints for kids.",
    colors: ["yellow", "green", "black"],
    category: ["kids"],
    type: ["jackets", "casual"],
  },
  {
    id: 19,
    title: "Men's Leather Shoes",
    rating: 4.9,
    price: 34.99,
    image: menshoes3,
    description: "A premium leather belt for a polished look.",
    colors: ["black", "brown"],
    category: ["men"],
    type: ["accessories", "formal"],
  },
  {
    id: 20,
    title: "Women's Casual High Heels",
    rating: 4.5,
    price: 39.99,
    image: womenshoes1,
    description: "Comfortable and chic flat shoes for daily wear.",
    colors: ["black", "beige", "blue"],
    category: ["women"],
    type: ["shoes", "casual"],
  },
  {
    id: 21,
    title: "Kids' Party Dress",
    rating: 4.8,
    price: 45.0,
    image: kids8,
    description: "Beautiful party dress for your little ones.",
    colors: ["pink", "white", "purple"],
    category: ["kids"],
    type: ["formal", "dresses"],
  },
  {
    id: 22,
    title: "Men's jackets",
    rating: 4.4,
    price: 18.99,
    image: menpants3,
    description: "Lightweight and breathable shorts for workouts.",
    colors: ["black", "gray", "blue"],
    category: ["men"],
    type: ["pants", "casual"],
  },
  {
    id: 23,
    title: "Women's Evening Clutch",
    rating: 4.6,
    price: 49.99,
    image: womensuits4,
    description: "Elegant clutch to complement evening attire.",
    colors: ["gold", "silver", "black"],
    category: ["women"],
    type: ["accessories", "formal"],
  },
  {
    id: 24,
    title: "Kids' Simple Dress",
    rating: 4.5,
    price: 22.99,
    image: kids6,
    description: "Comfortable denim shorts for active kids.",
    colors: ["blue", "black"],
    category: ["kids"],
    type: ["pants", "casual"],
  },
  {
    id: 25,
    title: "Men's Waterproof Boots",
    rating: 4.7,
    price: 89.99,
    image: womenshoes1,
    description: "Durable boots designed for all-weather use.",
    colors: ["brown", "black"],
    category: ["men"],
    type: ["shoes", "casual"],
  },
  {
    id: 26,
    title: "Kids Summer Dresses",
    rating: 4.3,
    price: 14.99,
    image: kidsdress,
    description: "Light and breezy Kids Summer Dresses.",
    colors: ["beige", "white", "blue"],
    category: ["women"],
    type: ["accessories", "casual"],
  },
  {
    id: 27,
    title: "Kids' Winter shoes",
    rating: 4.6,
    price: 9.99,
    image: kidsshoes1,
    description: "Soft gloves to keep little hands warm in winter.",
    colors: ["red", "blue", "green"],
    category: ["kids"],
    type: ["accessories", "casual"],
  },
  {
    id: 28,
    title: "Men's Casual Polo Shirt",
    rating: 4.5,
    price: 29.99,
    image: mencasual8,
    description: "Classic polo shirt for a smart-casual look.",
    colors: ["blue", "white", "red"],
    category: ["men"],
    type: ["shirts", "casual"],
  },
  {
    id: 29,
    title: "Women's Floral Maxi Skirt",
    rating: 4.8,
    price: 59.99,
    image: women3,
    description: "Flowy maxi dress with a beautiful floral pattern.",
    colors: ["blue", "pink", "white"],
    category: ["women"],
    type: ["formal", "dresses"],
  },
  {
    id: 30,
    title: "Kids' Soft Cotton Pajamas",
    rating: 4.7,
    price: 19.99,
    image: kids3,
    description: "Soft and comfortable pajamas for a good night's sleep.",
    colors: ["blue", "yellow", "pink"],
    category: ["kids"],
    type: ["casual", "nightwear"],
  },
  {
    id: 31,
    title: "Kids' Flower Girl Dress",
    rating: 4.9,
    price: 65.0,
    image: kids11,
    description: "Elegant flower girl dress for weddings and formal events.",
    colors: ["pink", "white"],
    category: ["kids"],
    type: ["formal", "dresses"],
  },
  {
    id: 32,
    title: "Kids' Casual Summer Dress",
    rating: 4.7,
    price: 25.0,
    image: kids2,
    description: "Lightweight and colorful dress for warm summer days.",
    colors: ["yellow", "blue", "green"],
    category: ["kids"],
    type: ["casual", "dresses"],
  },
  {
    id: 33,
    title: "Kids' Sports Sneakers",
    rating: 4.8,
    price: 32.99,
    image: kidsshoes2,
    description: "Durable sneakers designed for active kids.",
    colors: ["white", "blue", "black"],
    category: ["kids"],
    type: ["shoes", "casual"],
  },
  {
    id: 34,
    title: "Kids' Rain Boots",
    rating: 4.6,
    price: 27.99,
    image: kidsshoes3,
    description: "Waterproof rain boots for rainy adventures.",
    colors: ["yellow", "blue", "red"],
    category: ["kids"],
    type: ["shoes", "casual"],
  },
  {
    id: 35,
    title: "Men's Warm Winter Scarf",
    rating: 4.4,
    price: 14.99,
    image: mencasual3,
    description: "Soft scarf for cold winter days.",
    colors: ["gray", "black", "brown"],
    category: ["men"],
    type: ["accessories", "casual"],
  },
  {
    id: 36,
    title: "Men's Padded Jacket",
    rating: 4.8,
    price: 89.99,
    image: menjacket1,
    description: "Insulated jacket for maximum warmth in cold weather.",
    colors: ["blue", "black", "green"],
    category: ["men"],
    type: ["jackets", "casual"],
  },
  {
    id: 37,
    title: "Women's Lightweight Suit",
    rating: 4.7,
    price: 79.99,
    image: womensuits,
    description: "Elegant lightweight suit for business or casual wear.",
    colors: ["gray", "beige", "black"],
    category: ["women"],
    type: ["suits", "formal"],
  },
  {
    id: 38,
    title: "Women's Casual Flats",
    rating: 4.5,
    price: 35.99,
    image: womenshoes1,
    description: "Comfortable flats for all-day wear.",
    colors: ["brown", "black", "white"],
    category: ["women"],
    type: ["shoes", "casual"],
  },
  {
    id: 39,
    title: "Women's Winter Jacket",
    rating: 4.8,
    price: 99.99,
    image: womenjacket1,
    description: "Warm and stylish jacket for winter days.",
    colors: ["blue", "gray", "black"],
    category: ["women"],
    type: ["jackets", "casual"],
  },
  {
    id: 40,
    title: "Women's Casual Blazer",
    rating: 4.6,
    price: 45.99,
    image: womencasual1,
    description: "Light blazer for casual or business casual wear.",
    colors: ["white", "blue", "pink"],
    category: ["women"],
    type: ["jackets", "casual"],
  },
  {
    id: 41,
    title: "Men's Formal Pants",
    rating: 4.7,
    price: 49.99,
    image: menpants5,
    description: "Sophisticated pants perfect for office or formal occasions.",
    colors: ["black", "gray", "blue"],
    category: ["men"],
    type: ["pants", "formal"],
  },
  {
    id: 42,
    title: "Men's Hiking Boots",
    rating: 4.9,
    price: 99.99,
    image: menshoes2,
    description: "Rugged boots designed for long hikes.",
    colors: ["brown", "black", "gray"],
    category: ["men"],
    type: ["shoes", "casual"],
  },
  {
    id: 43,
    title: "Kids' Bright Sandals",
    rating: 4.6,
    price: 19.99,
    image: kidsshoes7,
    description: "Colorful sandals for a fun summer.",
    colors: ["yellow", "pink", "blue"],
    category: ["kids"],
    type: ["shoes", "casual"],
  },
  {
    id: 44,
    title: "Women's Office Pants",
    rating: 4.8,
    price: 59.99,
    image: womensuits2,
    description: "Tailored pants for a professional look.",
    colors: ["black", "gray", "navy"],
    category: ["women"],
    type: ["pants", "formal"],
  },
];
